### ISSUE TITLE
docker simulation not working

### ISSUE THREAD

**Issue by aarontan-git** [romarcg/traversability_estimation_pioneer#1]
Hello,

I wish to see the gazebo simulation as well as the csv files generated.

To do so, should I do:
`docker pull romarcg/traversability-ros-ubuntu-gazebo`
or
`docker pull romarcg/traversability-ros-ubuntu-gazebo-pioneer`
?

I am following the second link with intructions provided at this [docker hub link](https://hub.docker.com/r/romarcg/traversability-ros-ubuntu-gazebo-pioneer).

To enter the docker container, I believe where you had:

`nvidia-docker run -it --env="DISPLAY" --env="QT_X11_NO_MITSHM=1" --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" -v /home/omar/Codes/traversability_docker/traversability-ros-ubuntu-gazebo-pioneer/volume:/volume --name="traversability_gazebo_task" traversability-ros-ubuntu-gazebo-pioneer`

It should be the following instead:

`nvidia-docker run -it --env="DISPLAY" --env="QT_X11_NO_MITSHM=1" --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" -v /home/omar/Codes/traversability_docker/traversability-ros-ubuntu-gazebo-pioneer/volume:/volume --name="traversability_gazebo_task" romarcg/traversability-ros-ubuntu-gazebo-pioneer`

Once I am in the docker container, I run the following:

`roslaunch simulate_traversability_core launch_simulations.launch headless:=true gui:=true world_name:=custom1 dataset_type:=training number_tries:=50`

Which gives me the following error message (I am also not seeing csv files generated)

```
[ INFO] [1561472689.311174152]: Finished loading Gazebo ROS API Plugin.
[Msg] Waiting for master.
[ INFO] [1561472689.311682550]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 172.17.0.2
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  30
  Current serial number in output stream:  31
process[gazebo_gui-3]: started with pid [1034]
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
Aborted (core dumped)
[gazebo-2] process has died [pid 1015, exit code 134, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -r --verbose /root/catkin_ws/src/simulate_traversability/gazebo/models/heightmaps/custom1.world __name:=gazebo __log:=/root/.ros/log/fc033b98-9754-11e9-8070-0242ac110002/gazebo-2.log].
log file: /root/.ros/log/fc033b98-9754-11e9-8070-0242ac110002/gazebo-2*.log
[gazebo_gui-3] process has died [pid 1034, exit code 255, cmd /opt/ros/kinetic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/root/.ros/log/fc033b98-9754-11e9-8070-0242ac110002/gazebo_gui-3.log].
log file: /root/.ros/log/fc033b98-9754-11e9-8070-0242ac110002/gazebo_gui-3*.log
process[spawn_urdf-4]: started with pid [1115]
process[robot_state_publisher-5]: started with pid [1140]
ERROR: cannot launch node of type [simulate_traversability_core/run_simulation.py]: can't locate node [run_simulation.py] in package [simulate_traversability_core]
```
Could you please provide me some insight?

Thank you,
Aaron

**Comment by aarontan-git** [comment]
I have resolved the simulation issue by copying the simulation folder in to my own ros+gazebo setup. 

If possible, please provide more insight on how to utilize your docker containers in the future - there may be other people including myself who is still interested in the workings of this project. Thank you for your work!

**Comment by romarcg** [comment]
Hi,

that error has to do with the container not finding the correct gl 
driver/files in your host to perform to launch the simulation gui.

At that time I was using nvidia-docker (v1) and running the container 
with nvidia-docker run. This solved the issue because nvidia-docker 
(roughly speaking) takes care of linking those files.
