### ISSUE TITLE
mayavi version

### ISSUE THREAD

**Issue by aarontan-git** [romarcg/traversability_estimation_pioneer#4]
hello,

Can I know which version of Mayavi you used with this repo? It is not stated [here](http://romarcg.xyz/traversability_estimation/)

Thank you,
Aaron

**Comment by romarcg** [comment]
I ha several issues installing mayavi and a proper backend (qt). I 
installed mayavi2 downgrading some libraries to make it work. I used a 
separated environment to set all the needed libraries up.

**Comment by aarontan-git** [comment]
Thanks for your reply.

Could you provide some more details on the environment and library versions you used?

**Comment by romarcg** [comment]
I don't have that environment active anymore, but these were the setup: 
python 3.6, qt4, pyqt4.12, vtk7, mayavi2
