### ISSUE TITLE
visualizing t_graph_cnn.gpickle

### ISSUE THREAD

**Issue by aarontan-git** [romarcg/traversability_estimation_pioneer#5]
I am interested in visualizing the gpickle file (t_graph_cnn.gpickle) that is generated by *def generate_traversability_graph_cnn(fitted, heightmap_png, edges, resize, stride, neighbours)*

Could you provide some insight on what you mean by the following comments in evaluation.py? More specifically, what do you mean by *use dot t_graph.dot -Tx11 -Kneato*?

lines 318-332
```
    # to save the graph in pygraphviz for visualization
    nodes_positions_gviz = [ str(j)+','+str(-i)+'!' for i in range(0, hm_rows) for j in range(0,hm_cols)]
    #attr_positions = dict (zip(np.unique(full_data["patch"]),nodes_positions))
    attr_positions = dict (zip(np.unique(full_data["patch"]),nodes_positions_gviz))
    nx.set_node_attributes(G,"pos",attr_positions)
    ##nx.draw(G,nx.get_node_attributes(G,'pos'))
    #A=nx.drawing.nx_agraph.to_agraph(G)
    #A.write('t_graph_cnn.dot') 
    nx.write_gpickle(G, "t_graph_cnn.gpickle")
    
    # to visualize the graph in graphviz (and forcing to use our position for the nodes), use: 
    # dot t_graph.dot -Tx11 -Kneato
    
    # to read a dot file we shlould use:
    #G = nx.drawing.nx_agraph.read_dot('t_graph_cnn.dot')
```

**Comment by romarcg** [comment]
To visualize the graph, you can save it in dot format (use the tools in 
nx.drawing package). Then, use the dot application to open such file 
(i.e. the graph). The command I placed in the comments displays the 
graph in a grid like way, i.e. dot name_file.dot -Tx11 -Kneato.
