### ISSUE TITLE
visualization.py

### ISSUE THREAD

**Issue by aarontan-git** [romarcg/traversability_estimation_pioneer#6]
Hello,

I tried running the visualization.py file and it seems there are missing files in your repo.

Below is the error message

```
Traceback (most recent call last):
  File "visualization.py", line 925, in <module>
    visualizeReachabilityonTerrain(terrain, "inputs/reachability/quarry_stride_14-0.95-(8, 20)-reach.yaml", offset, pixelsize, stride, (r_x,r_y,4.7,0.8,230), 0.2, out_name = "quarry_stride_14-0.95-(8, 20)-reach")
  File "visualization.py", line 616, in visualizeReachabilityonTerrain
    with open(reachability_file_yaml, 'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'inputs/reachability/quarry_stride_14-0.95-(8, 20)-reach.yaml'
```

I am not sure where I can find these yaml files.

Please let me know!

Thank you,
Aaron

**Comment by romarcg** [comment]
Hi,

Those files are in the visualization / inputs / paths / 
(quarry_pioneer_9) and they represent a "reachability" visualization we 
devised to indecate how far can the robot moves by employing the local 
estimations of traversability and the proposed graph-based path 
planning aproach.
