### ISSUE TITLE
traversability_graph 32 orientations?

### ISSUE THREAD

**Issue by aarontan-git** [romarcg/traversability_estimation_pioneer#9]
Hello,

I noticed in your package that you can generate traversability maps up to 32 orientations.

Is it possible to do the same for generating the traversability graph? I noticed in your comment, you only stated either 4 or 8 directions. Is it possible to generate a traversability graph with 32 orientations as well?

Thank you

**Comment by romarcg** [comment]
Hello,

We used 4 or 8 because we wanted an evenly distributed graph (a uniform lattice). You can certainly build a graph with more directions; however you must find an interpretation for that. 

Cheers,
